export const categories = [
  'Auto',
  'Business',
  'Classic',
  'Comedy',
  'Documentary',
  'Education',
  'Entertainment',
  'Family',
  'Fashion',
  'Food',
  'General',
  'Health',
  'History',
  'Hobby',
  'Kids',
  'Legislative',
  'Lifestyle',
  'Local',
  'Movies',
  'Music',
  'News',
  'Quiz',
  'Religious',
  'Sci-Fi',
  'Shop',
  'Sport',
  'Travel',
  'Weather',
  'Other'
]

interface ILanguageAndCountry {
  [key: string]: string
}

export const languages: ILanguageAndCountry = {
  Akan: 'aka',
  Albanian: 'sqi',
  Amharic: 'amh',
  Arabic: 'ara',
  Armenian: 'hye',
  'Assyrian Neo-Aramaic': 'aii',
  Azerbaijani: 'aze',
  Bashkir: 'bak',
  Bengali: 'ben',
  Bosnian: 'bos',
  Bulgarian: 'bul',
  Burmese: 'mya',
  Catalan: 'cat',
  Chinese: 'zho',
  Croatian: 'hrv',
  Czech: 'ces',
  Danish: 'dan',
  Dutch: 'nld',
  English: 'eng',
  Estonian: 'est',
  Faroese: 'fao',
  Finnish: 'fin',
  French: 'fra',
  Galician: 'glg',
  Georgian: 'kat',
  German: 'deu',
  Hebrew: 'heb',
  Hindi: 'hin',
  Hungarian: 'hun',
  Icelandic: 'isl',
  Indonesian: 'ind',
  Inuktitut: 'iku',
  Italian: 'ita',
  Japanese: 'jpn',
  Javanese: 'jav',
  Kannada: 'kan',
  Kazakh: 'kaz',
  Khmer: 'khm',
  Kinyarwanda: 'kin',
  Korean: 'kor',
  Kurdish: 'kur',
  Lao: 'lao',
  Latvian: 'lav',
  Lithuanian: 'lit',
  Luxembourgish: 'ltz',
  Macedonian: 'mkd',
  'Malay (macrolanguage)': 'msa',
  Malayalam: 'mal',
  'Mandarin Chinese': 'cmn',
  Maori: 'mri',
  'Min Nan Chinese': 'nan',
  'Modern Greek (1453-)': 'ell',
  Mongolian: 'mon',
  Montenegrin: 'cnr',
  'Nepali (macrolanguage)': 'nep',
  'Norwegian Bokmål': 'nob',
  Panjabi: 'pan',
  Persian: 'fas',
  Polish: 'pol',
  Portuguese: 'por',
  Pushto: 'pus',
  Romanian: 'ron',
  'Russian	404	': 'rus',
  Serbian: 'srp',
  Sinhala: 'sin',
  Slovak: 'slk',
  Slovenian: 'slv',
  Somali: 'som',
  Spanish: 'spa',
  Swedish: 'swe',
  Tagalog: 'tgl',
  Tamil: 'tam',
  Thai: 'tha',
  Turkish: 'tur',
  Turkmen: 'tuk',
  Ukrainian: 'ukr',
  Urdu: 'urd',
  Uzbek: 'uzb',
  Vietnamese: 'vie',
  'Western Frisian': 'fry',
  'Yue Chinese': 'yue',
  Undefined: 'undefined'
}

export const countries: ILanguageAndCountry = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  'American Samoa': 'as',
  Andorra: 'ad',
  Angola: 'ao',
  Anguilla: 'ai',
  'Antigua & Barbuda': 'ag',
  Argentina: 'ar',
  Armenia: 'am',
  Aruba: 'aw',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bahamas: 'bs',
  Bahrain: 'bh',
  Bangladesh: 'bd',
  Barbados: 'bb',
  Belarus: 'by',
  Belgium: 'be',
  Belize: 'bz',
  Benin: 'bj',
  Bermuda: 'bm',
  Bhutan: 'bt',
  Bolivia: 'bo',
  Bosnia: 'ba',
  Botswana: 'bw',
  Brazil: 'br',
  'British Virgin Islands': 'vg',
  Brunei: 'bn',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Cambodia: 'kh',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  'Cayman Islands': 'ky',
  'Central African Republic': 'cf',
  Chad: 'td',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Comoros: 'km',
  'Congo - Brazzaville': 'cg',
  'Congo - Kinshasa': 'cd',
  'Cook Islands': 'ck',
  'Costa Rica': 'cr',
  Croatia: 'hr',
  Cuba: 'cu',
  Curaçao: 'cw',
  Cyprus: 'cy',
  Czechia: 'cz',
  'Côte d’Ivoire': 'ci',
  Denmark: 'dk',
  Djibouti: 'dj',
  Dominica: 'dm',
  'Dominican Republic': 'do',
  Ecuador: 'ec',
  Egypt: 'eg',
  'El Salvador': 'sv',
  'Equatorial Guinea': 'gq',
  Eritrea: 'er',
  Estonia: 'ee',
  Eswatini: 'sz',
  Ethiopia: 'et',
  'Faroe Islands': 'fo',
  Fiji: 'fj',
  Finland: 'fi',
  France: 'fr',
  'French Guiana': 'gf',
  'French Polynesia': 'pf',
  'French Southern Territories': 'tf',
  Gabon: 'ga',
  Gambia: 'gm',
  Georgia: 'ge',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Greenland: 'gl',
  Grenada: 'gd',
  Guadeloupe: 'gp',
  Guam: 'gu',
  Guatemala: 'gt',
  Guinea: 'gn',
  'Guinea-Bissau': 'gw',
  Haiti: 'ht',
  Honduras: 'hn',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  '🌍International': 'int',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kiribati: 'ki',
  Kosovo: 'xk',
  Kuwait: 'kw',
  Kyrgyzstan: 'kg',
  'Laos 0': 'la',
  Latvia: 'lv',
  Lebanon: 'lb',
  Lesotho: 'ls',
  Liberia: 'lr',
  Libya: 'ly',
  Liechtenstein: 'li',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Macao: 'mo',
  Madagascar: 'mg',
  Malawi: 'mw',
  Malaysia: 'my',
  Maldives: 'mv',
  Mali: 'ml',
  Malta: 'mt',
  'Marshall Islands': 'mh',
  Martinique: 'mq',
  Mauritania: 'mr',
  Mauritius: 'mu',
  Mayotte: 'yt',
  Mexico: 'mx',
  Micronesia: 'fm',
  Moldova: 'md',
  Monaco: 'mc',
  Mongolia: 'mn',
  Montenegro: 'me',
  Montserrat: 'ms',
  Morocco: 'ma',
  Mozambique: 'mz',
  Myanmar: 'mm',
  Namibia: 'na',
  Nauru: 'nr',
  Nepal: 'np',
  Netherlands: 'nl',
  'New Caledonia': 'nc',
  'New Zealand': 'nz',
  Nicaragua: 'ni',
  Niger: 'ne',
  Nigeria: 'ng',
  Niue: 'nu',
  'Norfolk Island': 'nf',
  'North Korea': 'kp',
  'North Macedonia': 'mk',
  'Northern Mariana Islands': 'mp',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Palau: 'pw',
  Palestine: 'ps',
  Panama: 'pa',
  'Papua New Guinea': 'pg',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  'Pitcairn Islands': 'pn',
  Poland: 'pl',
  Portugal: 'pt',
  'Puerto Rico': 'pr',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  Rwanda: 'rw',
  Réunion: 're',
  Samoa: 'ws',
  'San Marino': 'sm',
  'Saudi Arabia': 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  Seychelles: 'sc',
  'Sierra Leone': 'sl',
  Singapore: 'sg',
  'Sint Maarten': 'sx',
  Slovakia: 'sk',
  Slovenia: 'si',
  'Solomon Islands': 'sb',
  Somalia: 'so',
  'South Africa': 'za',
  'South Korea': 'kr',
  'South Sudan': 'ss',
  Spain: 'es',
  SriLanka: 'lk',
  'St.Barthélemy': 'bl',
  'St.Helena': 'sh',
  'St.Kitts & Nevis': 'kn',
  'St.Lucia': 'lc',
  'St.Martin': 'mf',
  'St.Pierre & Miquelon': 'pm',
  'St.Vincent & Grenadines': 'vc',
  Sudan: 'sd',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  'São Tomé & Príncipe': 'st',
  Tajikistan: 'tj',
  Tanzania: 'tz',
  Thailand: 'th',
  'Timor-Leste': 'tl',
  Togo: 'tg',
  Tokelau: 'tk',
  Tonga: 'to',
  'Trinidad & Tobago': 'tt',
  Tunisia: 'tn',
  Turkey: 'tr',
  Turkmenistan: 'tm',
  'Turks & Caicos Islands': 'tc',
  Tuvalu: 'tv',
  'U.S. Virgin Islands': 'vi',
  Uganda: 'ug',
  Ukraine: 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom': 'uk',
  'United States': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Vanuatu: 'vu',
  'Vatican City': 'va',
  Venezuela: 've',
  Vietnam: 'vn',
  'Wallis & Futuna': 'wf',
  'Western Sahara': 'eh',
  Yemen: 'ye',
  Zambia: 'zm',
  Zimbabwe: 'zw',
  'Åland Islands': 'ax',
  Undefined: 'undefined'
}
